8 cloning an existing repository
dfe-analytical-services/git-academy pull request #14
Opened 2024-11-13 14:14 UTC by Lsnaathorst1

Adding cloning an existing repository information 

(May want to change which headers automatically get a line/don't get a line in future!)

## Overview of changes
Guide and tasks for cloning an existing repo 

## Issue ticket number/s and link
Cloning an existing repository #8

2024-11-14 13:24 UTC, rmbielby requested changes
Looks good. Few minor comments / suggestions

2024-11-14 13:24 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +### To Clone Using RStudio:
How about we try using a tabset panel for the different methods?

https://quarto.org/docs/interactive/layout.html#tabset-panel

2024-11-14 13:24 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +Check the Files pane in RStudio to see if the repository files have been cloned to your local machine. The files pane normally opens in the right-hand bottom corner of RStudio.
I think for this one we should be IDE agnostic. Analysts could be working in R, Python, SQL, html+css, etc, so for the git bash one, I think we shouldn't use R-Studio at all.

Instructions for checking the repo in git bash would be along the lines of:

- Navigate into the repo directory, e.g. `cd git-academy-sandbox`
- You should now see the current branch name (e.g. main) at the end of the filepath
- type `git log` to view recent commits or `git status` to check the state of the cloned repository (at this point it should say everything's up to date as you haven't made any changes to anything yet)

2024-11-14 13:24 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +This section will guide you through the process of cloning a GitHub repository. Cloning a repository means making a local copy of a project that exists on GitHub. This enables you to make changes and
"that exists on GitHub" -> "that exists on a "remote" DevOps server such as Axure DevOps, GitHub or GitLab"

2024-11-18 11:51 UTC, Lsnaathorst1 commented
@rmbielby suggested changes made and tried to tidy the headings a bit too :)

2024-11-19 17:16 UTC, rmbielby requested changes
Nice. Just a few more minor comments though! :-)

2024-11-19 17:16 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +This section will guide you through the process of cloning a GitHub repository. Cloning a repository means making a local copy of a project that exists on a "remote" DevOps server such as Axure DevOp
Typo: Axure -> Azure

2024-11-19 17:16 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +## Step 1: Clone the Repository
This feels more like "Get the repository clone link" rather then "Clone the repository"

2024-11-19 17:16 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +### Step 2a: Open RStudio
I don't want to be R centric, so can we shift Git bash to be the first panel.

2024-11-19 17:16 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +-   You should now see the current branch name (e.g. main) at the end of the file path.
Could add a small image to show what this looks like.

2024-11-20 10:50 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +This enables you to make changes and test locally before pushing to be approved and merged with the main branch on GitHub.
Wonder if this is too much extra info. They may not know about pushing, merging and approving yet. I'd be tempted to bring it back to the very specific basics:

"If you have a repository on Azure DevOps, GitHub or GitLab, you generally can't edit or run your work on those platforms, so if you need to work with the contents of a repo, you'll usually need to make a clone."

2024-11-20 10:51 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +b\. Click the "Code" green button and copy the URL (HTTPS link).
The colour of the button depends on your theme (mine's blue), so maybe just remove green here.

2024-11-20 10:53 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +
This needs to be all one line

2024-11-20 10:55 UTC, rmbielby commented on ch2-git-basics/cloning.qmd
> +-   Type **git log** to view recent commits or **git status** to check the state of the cloned repository (at this point, it should say everything is up to date, as you haven't made any changes yet).
Need to add "(and press q to exit git log)" after "to view recent commits"

2024-11-21 10:28 UTC, Lsnaathorst1 commented
@rmbielby I think this is ready for another review when you're ready

2024-11-21 13:29 UTC, rmbielby approved these changes

2024-11-21 13:29 UTC, merged