20 exploring a repository on GitHub
dfe-analytical-services/git-academy pull request #22
Opened 2024-12-11 15:02 UTC by Lsnaathorst1

Adding the Exploring a repository page.

I have added the sections currently listed in the log. There's a few places where things overlap, so would be especially good to know if this is too much info for one page and/or too repetitive where the first instruction for each tells the user to go to the repo.

Also on the amount of screengrabs - is it too much, or too little if we want one for everything?

2024-12-13 17:52 UTC, rmbielby requested changes
Looks good. Structural thoughts are that, yes it's too much for one page, so let's split it into 4 different pages:
- Switching branches on GitHub
- Viewing a file on GitHub
- Editing a file on GitHub
- Viewing the commit history on GitHub

I'm treating the start of each page as following on from the previous one, so to reduce the repetitiveness, you could have opening sentences for the 2nd, 3rd and 4th ones along the lines of:
"Still on the GitHub site for the github-sandbox repository..." and equivalent and remove that first step from each one.

2025-01-06 12:01 UTC, Lsnaathorst1 commented
@rmbielby this is ready for a re-review when you have a sec!

2025-01-08 10:16 UTC, rmbielby requested changes
Looking good. Just a handful of small comments.

2025-01-08 10:16 UTC, rmbielby commented on git-refresher/viewing-branches-github.qmd
> +1.  Navigate to the repository on GitHub. In this case, [Git-academy-sandbox](https://github.com/dfe-analytical-services/git-academy-sandbox).
```suggestion
1.  Navigate to the repository on GitHub. In this case, [Git-academy-sandbox](https://github.com/dfe-analytical-services/git-academy-sandbox){target="_blank"}.
```

2025-01-08 10:16 UTC, rmbielby commented on git-refresher/viewing-branches-github.qmd
> +1.  Navigate to the repository on GitHub. In this case, [Git-academy-sandbox](https://github.com/dfe-analytical-services/git-academy-sandbox).
Adding that should make it open in a new tab so that users don't lose sight of the guide when the click on the link.

2025-01-08 10:16 UTC, rmbielby commented on git-refresher/viewing-file-github.qmd
> +7. You will need to switch to the code tab to view and edit the raw contents of the file. The preview tab will show you a preview for supported files like Markdown and Quarto and the blame tab shows
"switch to the code tab" is a little bit confusing that there's a code tab along the top tab-set and then a code tab for each file tab-set. Could maybe just provide a line to give context at the start of this paragraph along the lines of 

> Each file will have a sub-set of the following views available to select above it: preview, code and blame.

Then maybe switch the language in the rest of 7 from "tab" to "view" to help differentiate from the overall Code tab.

2025-01-08 10:16 UTC, rmbielby commented on git-refresher/editing-file-github.qmd
> +8.  Click 'Commit changes' to save your edits and create a new commit. When you view the git-academy-log file, you should see that the boxes under 'Exploring a repository on Github' are now ticked.
I think add a call-out box at the end (probably important-level is most appropriate), saying that to have the online changes available locally, they'll need to do a pull (we can go back and add a link on the walkthrough step on pulling once we've written it).

2025-01-08 11:31 UTC, Lsnaathorst1 commented
@rmbielby updates made thanks :)

2025-01-08 12:04 UTC, rmbielby approved these changes

2025-01-08 12:04 UTC, merged