Add why use git section
dfe-analytical-services/git-academy pull request #3
Opened 2024-04-08 14:24 UTC by chfoster

Closes issue #2 - added text from onenote into Quarto file.

2024-04-12 15:33 UTC, rmbielby requested changes
I reckon we should make this more concise and just edit it down a whole bunch. Also feel like it'd be good to strip out some of the AI hyperbole like "dynamic landscape".

One thing I reckon it's worth trying is using a tabset panel instead of having it arranged as a page of text.

```
::: {.panel-tabset}
## Collaboration

## Clean development

## Version control

## Audit trails

:::
```

2024-04-12 15:34 UTC, rmbielby commented on ch1-introduction/why-use-git.qmd
> +## Branching
Feel like branching may be a term that a learner might not be familiar with by this point, so maybe a different title for this one like "Clean development"?

2024-05-02 08:15 UTC, chfoster commented
@rmbielby have edited, cut down wording and added panel-tabset (though I'm not sure it's the prettiest, I'm thinking accordions would look better if I can figure that out: 
![image](https://github.com/dfe-analytical-services/git-academy/assets/101197790/a652d674-26d9-4558-b267-94d3585c65ee)

2024-05-02 08:48 UTC, chfoster commented
@rmbielby Got an alternative though this might be worse for accessibility as they're coded using `<details> and <summary> ` rather than as headings: 
![image](https://github.com/dfe-analytical-services/git-academy/assets/101197790/f0163ad2-a620-40ce-a331-70f11c4a3a50)

2024-05-03 07:50 UTC, chfoster commented
> > @rmbielby have edited, cut down wording and added panel-tabset (though I'm not sure it's the prettiest, I'm thinking accordions would look better if I can figure that out: ![image](https://private-user-images.githubusercontent.com/101197790/327360070-a652d674-26d9-4558-b267-94d3585c65ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjcyMDYsIm5iZiI6MTcxNDY2NjkwNiwicGF0aCI6Ii8xMDExOTc3OTAvMzI3MzYwMDcwLWE2NTJkNjc0LTI2ZDktNDU1OC1iMjY3LTk0ZDM1ODVjNjVlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNjIxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzA3Nzc0YzE2OTc0MmEzMDEwOTdmY2Y2YmIzYmYwMzYxNTNlOTkyNjU2MmNjYTlhMTQwMGExMTI3ODViMDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AYPXF2esEyKEt6d42IaxfR1xxqrthttATIjpbE7FR-g)
> 
> Can happily use keyboard navigation to get around that one at least. have you tried keyboard navigation around the second one?

You can tab to each section and use enter to expand/collapse so not too bad

2024-05-08 10:58 UTC, chfoster commented
Used custom CSS to made details section names actual h2 headers :)
![git-academy-1](https://github.com/dfe-analytical-services/git-academy/assets/101197790/4d5b5a92-1fb6-42e0-932b-784457e7a019)

2024-05-15 09:02 UTC, rmbielby requested changes

2024-05-15 09:02 UTC, rmbielby commented on ch1-introduction/custom.css
> +}
Think this needs a blank line at the end of the file, otherwise some browsers may not read line 12 in (i.e. line 12 needs a carriage return).

2024-05-15 13:37 UTC, rmbielby approved these changes

2024-05-15 13:39 UTC, merged